apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-mediawiki-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: {{ .Values.db_persistentvolume_path.hostPath.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
           operator: In
           values:
           - {{ .Values.db_hostpath_node.nodename }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-mediawiki-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage