apiVersion: v1
kind: Service
metadata:
  name: my-mediawiki-svc
  labels:
    app: my-mediawiki
spec:
  externalIPs:
  - 10.10.171.3
  type: NodePort
  ports:
    - targetPort: 80
      port: 8096
      protocol: TCP
  selector:
    app: my-mediawiki